name: ECOZ2 C Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Build linux
      if: ${{ matrix.os == 'ubuntu-latest' }}
      run: |
        CC=gcc make
        cd _out/bin/
        zip "${{github.workspace}}/ecoz2-linux.zip" *

    - name: Build macos
      if: ${{ matrix.os == 'macos-latest' }}
      run: |
        CC=gcc-9 make
        cd _out/bin/
        zip "${{github.workspace}}/ecoz2-macos.zip" *

    - name: Release linux
      if: ${{ matrix.os == 'ubuntu-latest' }}
      uses: sondreb/action-release@master
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        draft: true
        prerelease: true
        body: 'This is a pre-release'
        name: "Draft Release"
        tag: ${{ github.ref }}
        files: "ecoz2-linux.zip"

    - name: Release macos
      if: ${{ matrix.os == 'macos-latest' }}
      uses: sondreb/action-release@master
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        draft: true
        prerelease: true
        body: 'This is a pre-release'
        name: "Draft Release"
        tag: ${{ github.ref }}
        files: "ecoz2-macos.zip"
